### ISSUE TITLE
 invalid conversion from ‘char’ to ‘cublasFillMode_t’ in cusolverDn.c:447:85

### ISSUE THREAD

**Issue by aheumaier** [prasunanand/rbcuda#2]
Hi Prasun,

Following your install instructions on Ubuntu 18.04 LTS 
using libcudart9.1(Version: 9.1.85-3ubuntu1) and gcc 7.3-16 (Ubuntu 7.3.0-16ubuntu3) the following error occurs: 
**../../../../ext/rbcuda/solver/cusolverDn.c:447:85: error: invalid conversion from ‘char’ to ‘cublasFillMode_t’** [-fpermissive]

while running 

``` bash
rake compile
cd tmp/x86_64-linux-gnu/rbcuda/2.5.1
/usr/bin/make
compiling ../../../../ext/rbcuda/rbcuda.cpp
In file included from ../../../../ext/rbcuda/ruby_rbcuda.c:1970:0,
                 from ../../../../ext/rbcuda/rbcuda.cpp:31:
../../../../ext/rbcuda/solver/cusolverDn.c: In function ‘VALUE rb_cusolverDnDsytrd(VALUE, VALUE, VALUE, VALUE, VALUE, VALUE, VALUE, VALUE, VALUE, VALUE, VALUE, VALUE)’:
../../../../ext/rbcuda/solver/cusolverDn.c:447:85: error: invalid conversion from ‘char’ to ‘cublasFillMode_t’ [-fpermissive]
   cusolverStatus_t status = cusolverDnDsytrd(handler->handle, StringValuePtr(uplo)[0], NUM2INT(n), ptr_A->carray, NUM2INT(lda),
In file included from ../../../../ext/rbcuda/rbcuda.cpp:12:0:
/usr/include/cusolverDn.h:1056:30: note:   initializing argument 2 of ‘cusolverStatus_t cusolverDnDsytrd(cusolverDnHandle_t, cublasFillMode_t, int, double*, int, double*, double*, double*, double*, int, int*)’
 cusolverStatus_t CUSOLVERAPI cusolverDnDsytrd(
                              ^~~~~~~~~~~~~~~~
Makefile:240: recipe for target 'rbcuda.o' failed
make: *** [rbcuda.o] Error 1
rake aborted!
Command failed with status (2): [/usr/bin/make...]
/var/lib/gems/2.5.0/gems/rake-compiler-0.9.9/lib/rake/extensiontask.rb:157:in `block (2 levels) in define_compile_tasks'
/var/lib/gems/2.5.0/gems/rake-compiler-0.9.9/lib/rake/extensiontask.rb:156:in `block in define_compile_tasks'
/var/lib/gems/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => compile => compile:x86_64-linux-gnu => compile:rbcuda:x86_64-linux-gnu => copy:rbcuda:x86_64-linux-gnu:2.5.1 => tmp/x86_64-linux-gnu/rbcuda/2.5.1/rbcuda.so
```

Feel free to reach out for more information as needed . Happy to help !

- Andreas

**Comment by prasunanand** [comment]
Hi @aheumaier , Do you have cublas installed ?

**Comment by aheumaier** [comment]
Sure
~$ sudo aptitude show libcublas9.1
Paket: libcublas9.1
Version: 9.1.85-3ubuntu1

`~$ ll /usr/lib/x86_64-linux-gnu/libcublas.so
libcublas.so         libcublas.so.9.1     libcublas.so.9.1.85`

`~$ ll /usr/lib/x86_64-linux-gnu/libcublas.so
lrwxrwxrwx 1 root root 16 Apr 26 14:33 /usr/lib/x86_64-linux-gnu/libcublas.so -> libcublas.so.9.1`

`~$ ll /usr/lib/x86_64-linux-gnu/libcublas.so.9.1
lrwxrwxrwx 1 root root 19 Apr 26 14:33 /usr/lib/x86_64-linux-gnu/libcublas.so.9.1 -> libcublas.so.9.1.85`

`~$ ll /usr/lib/x86_64-linux-gnu/libcublas.so.9.1.85
-rw-r--r-- 1 root root 54035688 Dez  2  2017 /usr/lib/x86_64-linux-gnu/libcublas.so.9.1.85`

**Comment by prasunanand** [comment]
Thanks for reporting the issue :)
It has been resolved https://github.com/prasunanand/rbcuda/commit/5900739b93a4ffe33eb2c8310c2db4c109eb27b3

**Comment by prasunanand** [comment]
Nvidia has modified its API for CuSolver.

**Comment by aheumaier** [comment]
Works for me. Thanks! Expected kinda like that.
